changes how parameters are received
bukinoshita/holiday pull request #5
Opened 2017-03-09 03:37 UTC by vcapretz

lots of changes were required, all tests pass (even new ones)

*the is-holiday project needs changes after this PR is merged*

closes #4

2017-03-09 15:31 UTC, bukinoshita requested changes
It's looking great! Some minor changes and if possible to update the README as well, would be great since the API has changed.

2017-03-09 15:31 UTC, bukinoshita commented on index.js
> +const holiday = obj => {
If I run:
```js
holiday()
```

it returns me this error:
```bash
/Users/buuh7921/github/holiday/index.js:7
  const {year = date.getFullYear(), month, day, country = 'us'} = obj
                                                                  ^
TypeError: Cannot match against 'undefined' or 'null'.
```

You probably want to use it like this:
```js
const holiday = (opts = {}) => {
  ...
}
```

Ps: change `obj` to `opts`

2017-03-09 15:31 UTC, bukinoshita commented on index.js
> +const holiday = obj => {
Also create a test for that, running the function without any arguments should return the entire year

2017-03-12 00:50 UTC, vcapretz commented
@bukinoshita I also changed the output for the entire year because it was just an array and we could know the day and month of each holiday (we will need it to `is-holiday`)

2017-03-12 02:39 UTC, bukinoshita approved these changes

2017-03-12 02:40 UTC, bukinoshita commented
Looks great @vcapretz 🎉

2017-03-12 02:40 UTC, merged